import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NextUIProviderClient from "@/providers/NextUIProviderClient";
import ProvidersClient from "@/providers/ProvidersClient";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  weight: ["200", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" className="dark">
    <html lang="en" className="dark">
      <body className={poppins.className}>
        <NextUIProviderClient>
          <ProvidersClient>{children}</ProvidersClient>
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                padding: "15px 15px",
              },
            }}
          />
        </NextUIProviderClient>
      </body>
    </html>
  );
}
